common/urls.py
from django.urls import path
from.import views
app_name='common'

urlpatterns=[
  path('master',views.home,name='cmaster'),
  path('home',views.customer_login,name='chome'),
  path('customersignup',views.customer_signup,name='customer_signup'),
  path('projecthome',views.project_home,name='home'),
  path('sellerlogin',views.seller_login,name='seller_login'),
  path('sellersignup',views.seller_signup,name='seller_signup'),
  path('customer_login',views.customer_login,name='customer_login'),
  path('index',views.index,name='index'),
  path('float',views.float,name='float'),
]

customer/urls.py
from django.urls import path
from. import views 
app_name='customer'

urlpatterns=[
 path('home',views.home,name='home'),
 path('changepassword',views.change_password,name='changepassword'),
 path('checkout',views.checkout),
 path('mycart',views.my_cart,name='cart1'),
 path('myorder',views.my_order),
 path('productdetails/<int:pid>',views.product_details,name="productdetails1"),
 path('profile',views.profile,name='profile'),
 path('master',views.master),
 path('get_total',views.get_total,name='get_total'),
 path('remove_cart/<int:cid>',views.remove_cart_item,name='remove_cart_item'),
 path('logout',views.log_out,name='logout'),
 path('profile_ajax',views.profile_ajax,name='profile_ajax'),
]

ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('customer.urls')),
    path('ecom_admin/',include('ecom_admin.urls')),
    path('seller/',include('seller.urls')),
    path('',include('common.urls')),
    path('lightapi/',include('lightapi.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from common.models import Customer
from seller.models import Product

# Create your models here.


class cart(models.Model):
  customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
  Product = models.ForeignKey(Product,on_delete=models.CASCADE)

  class Meta:
      db_table = 'cart_tb'

customer/views.py
from django.shortcuts import render,redirect
from common.models import Customer
from seller.models import Product
from customer.models import cart
from django.http import JsonResponse
from .decorator import auth_customer

# Create your views here.
def home(request):
    customer_details = Customer.objects.get(id=request.session['customer'])
    product = Product.objects.all()
    cname = customer_details.first_name+' '+customer_details.second_name
    context = {
        'name':cname,
        'products':product,
    }
    return render(request,'customer/home.html',context)

def change_password(request):
    error_msg =''
    success_msg =''
    if request.method == 'POST':
       old_password =request.POST['old_password'] 
       new_password =request.POST['new_password']
       conform_password =request.POST['conform_password']
       if new_password == conform_password:
        if len(new_password) > 8:
            customer = Customer.objects.get(id =request.session['customer'])
            if old_password == customer.password:
                Customer.objects.filter(id =request.session['customer']).update(password =new_password)
                success_msg = 'successfully created new password'
            else:
                error_msg ='invalid password'
        else:
            error_msg = 'password should be minimum 8 characters'
       else:
        error_msg ='password does\'t match'
    return render(request,'customer/change password.html',{'erorr':error_msg,'success':success_msg} )

def checkout(request):
    return render(request,'customer/checkout.html')


@auth_customer
def my_cart(request):
    
    Cart =cart.objects.filter(customer_id =request.session['customer'])
   
    return render(request,'customer/my cart.html',{'cart':Cart})

def my_order(request):
    return render(request,'customer/my order.html')

def product_details(request,pid):
    product_details = Product.objects.get(id=pid)
    msg =''
    if request.method == 'POST':
        item =cart.objects.filter(customer=request.session['customer'],Product=pid).exists()
        if not item:

            cart_item = cart(customer_id =request.session['customer'],Product_id =pid)
            cart_item.save()
            return redirect('customer:cart1')
        else:
            msg='items already in cart'    
    return render(request,'customer/product details.html',{'details':product_details,'message':msg})
    

def profile(request):
    msg =""
    if request.method == 'POST':
      if request.POST['First_name'] and request.POST['Last_name'] and request.POST['address']:
        fname = request.POST['First_name']
        sname = request.POST['Last_name']
        address = request.POST['address']
        Customer.objects.filter(id =request.session['customer']).update(first_name=fname,second_name=sname,address=address)
        msg='Profile updated successfully'
           
      else:
       msg = 'please fill all the field before submitting'
        # print('No name submitted')
        
    customer_details = Customer.objects.get(id=request.session['customer'])

    return render(request,'customer/profile.html',{'profile':customer_details,'message':msg})


def master(request):
    return render(request,'customer/master.html')

def get_total(request):
    pid = request.POST['pid'] #pid is the [key] passed from ajax request
    qty = request.POST['qty']
    product = Product.objects.filter(id=pid).values('price')
    total_amount = int(qty)*product[0]['price']
    print(total_amount)
    return JsonResponse({'amount': total_amount})

def remove_cart_item(request,cid):
    item = cart.objects.get(id=cid)
    item.delete()
    return redirect('customer:cart1')

def log_out(request):
    del request.session['customer']
    request.session.flush()
    return redirect('common:cmaster')


def profile_ajax(request):
    proid = request.POST['proid']
    customer = Customer.objects.filter(id=proid).values('first_name','second_name','address')
    f_name =customer[0]['first_name']
    s_name =customer[0]['second_name']
    c_add =customer[0]['address']
    return JsonResponse({'f_name': f_name,'s_name': s_name,'c_add': c_add,})

customer/templates/customer/change password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style/style.css' %}">
  

</head>
<body>
  <div class="container">
    
      <div class="row g-0">
        
        <div class="col-md-4  mt-5 pt-5 rounded-3">
          <img src="{% static 'images/lohin-img.jpg' %}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body color mt-5 pt-5 rounded-3">
            <h5 class="card-title ms-5">customer password update</h5>
            <div class="mt-4 ms-4">
              <form method="post">
              {% csrf_token %}
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label">old password</label>
                  <input type="password" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" style="width: 50%;" name="old_password">
                  
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">new Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" style="width: 50%;" name="new_password">
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">conform Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" style="width: 50%;" name="conform_password">
                </div>
                <div class="mb-3 form-check">
                  <input type="checkbox" class="form-check-input" id="exampleCheck1">
                  <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-outline-danger mb-3" style="width: 25%;">change</button>
                {{ erorr }} {{ success }}
              </form>
            </div>
            <!-- <div class="modal-footer justify-content-center">
              <div class="mb-3">
             <span>create a new account?</span><a class="text-decoration-none text-danger" href="{% url 'common:seller_signup' %}" >sign up</a>
            </div>
            </div> -->
          </div>
        </div>
      </div>
    
  </div>
  
</body>
</html>

customer/templates/customer/checkout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'style/main.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-transparent">
      <div class="container-fluid">
        <a class="navbar-brand text-dark fw-bold" href="#"><span class="text-danger">L!ght</span>-k@rt</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <form class="d-flex" role="search">
            <input class="form-control me-2 rounded-pill" type="search" placeholder="Search" aria-label="Search" style="width:400px;">
            <button class="btn btn-outline-dark rounded-circle" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
          </form>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link text-dark fw-bold" href="#"><i class="fa-brands fa-dropbox fs-5 text-primary"></i> product</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark fw-bold" href="#"> <i class="fa-solid fa-cart-plus fs-5 text-info"></i> Cart</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark fw-bold" href="#"><i class="fa-solid fa-truck fs-5 text-danger"></i>  order</a>            
            </li>
            <!-- <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-user"></i>
              </a>
              <ul class="dropdown-menu dropdown-menu-end">
                <li><a class="dropdown-item" href="#">Login</a></li>
                <li><a class="dropdown-item" href="#"></a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul> -->
              <li class="nav-item">
                <a class="nav-link text-dark fw-bold" href="#"><i class="fa-solid fa-key fs-5 text-warning"></i>  change password</a>              
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark fw-bold" aria-current="page" href="#"><i class="fa-solid fa-lock fs-5 text-success"></i>  logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark fw-bold" aria-current="page" href="#"><i class="fa-solid fa-user fs-5 text-secondary"></i> profile</a>
              </li>
              </ul>
          
        </div>
      </div>
    </nav> 
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

customer/templates/customer/home.html
 {% extends "customer/master.html" %}
 {% load static %}
 {% block content %}
    <div class="row">
      <div class="col">
        <!-- <img src="{% static 'images/graph (1).png' %}" class="img-fluid" alt=""> -->
        <div class="mt-5 pt-5 ps-4">
          <h1 class="fw-bold text-color">Welcome {{ name }} to the world of light</h1>
          <h1 class="fw-bold text-color">be part of us and grow with us!!!!</h1>
        </div>
      

      </div>
      <div class="col">
        <img src="{% static 'images/main-removebg-preview.png' %}" class="img-fluid main-img" alt="">
      </div>
    </div>
    <div class="container">
    <div class="row">
      {% for product in products  %}
      <div class="col-sm-3">
        
        <div class="card border border-0">
          <a href="{% url 'customer:productdetails1' product.id %}">
          <img src="{{ product.image.url }}" class="card-img-top" alt="..."></a>
          <div class="card-body border border-0">
            <h5 class="card-title">{{ product.product_name}}</h5>
            <p class="card-text">{{ product.product_discription }}
            </p>
            <span class="text-muted fs-4"><s> <span class="text-dark">&#8377;</span> 1000 </s><span
                class="text-danger">350 OFF</span> </span>
  
            <div>
              <span class="text-danger fs-4"><span class="text-dark text-end">&#8377;</span>{{ product.price }}</span>
  
            </div>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
    <!-- Button trigger modal -->

{% endblock %}
<!-- Modal -->
<!-- <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header bg-danger">
        <h1 class="modal-title fs-5 text-light" id="exampleModalLabel">Add Product</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-2">
            <label for="exampleInputproductname" class="form-label">Product name</label>
            <input type="text" class="form-control form-control-sm" id="exampleInputproductname" aria-describedby="emailHelp" style="width: 70%;">
            
          </div>
          <div class="mb-2">
          <label for="exampleInputselect" class="form-label">product category</label>
          <select class="form-select form-select-sm" aria-label=".form-select-sm example" style="width: 70%;">
            <option selected>select product</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
          </select>
        </div>
          <div class="mb-2">
            <label for="exampleFormControlTextarea1" class="form-label">product discription</label>
            <textarea class="form-control form-control-sm" id="exampleFormControlTextarea1" rows="3" style="width: 70%;"></textarea>
          </div>
          <div class="mb-2">
            <label for="exampleInputquantity" class="form-label">quantity</label>
            <input type="number" class="form-control form-control-sm" id="exampleInputquantity" style="width: 25%;">
          </div>
          <div class="mb-2">
            <label for="exampleInputprice" class="form-label">price</label>
            <input type="tel" class="form-control form-control-sm" id="exampleInputprice" style="width: 25%;">
          </div>
          
          <div class="mb-2">
            <label for="exampleInputimg" class="form-label">Choose a image</label>
            <input type="file" class="form-control form-control-sm" id="exampleInputimg" style="width: 25%;">
          </div>
          <div class="mb-2 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
          </div>
          
        </form>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Add</button>
      </div>
    </div>
  </div>
</div> -->
    
   

customer/templates/customer/master.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'style/sellerhome.css' %}">
    <link rel="stylesheet" href="{% static 'style/main.css' %}">
    <link rel="stylesheet" href="{% static 'style/grid.css' %}">
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-transparent">
      <div class="container-fluid">
        <a class="navbar-brand text-dark fw-bold" href="#"><span class="text-danger">L!ght</span>-k@rt</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <form class="d-flex" role="search">
            <input class="form-control me-2 rounded-pill" type="search" placeholder="Search" aria-label="Search" style="width:400px;">
            <button class="btn btn-outline-dark rounded-circle" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
          </form>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
           
            <li class="nav-item mt-2 me-2">
              <a class="text-decoration-none text-dark fs-6 fw-bold" href="{% url 'customer:cart1' %}"><i class="fa-solid fa-truck fs-5 text-danger"></i> my cart</a></li>
            </li>
           
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-plus fs-5 text-danger"></i>
              </a>
              <ul class="dropdown-menu dropdown-menu-end">
                
                <li><a class="dropdown-item" href="#"><i class="fa-solid fa-truck-fast fs-5"></i>  Recent order</a></li>
                <li><a class="dropdown-item" href="#"><i class="fa-solid fa-calendar-plus fs-5"></i>   updatestock</a></li>
                <li><a class="dropdown-item" href="{% url 'customer:changepassword' %}"><i class="fa-solid fa-key fs-5 text-warning"></i>  change password</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'customer:logout' %}"><i class="fa-solid fa-lock fs-5 text-success"></i>  logout</a></li>
                <li><a class="dropdown-item" href="{% url 'customer:profile' %}"><i class="fa-solid fa-user fs-5 text-secondary"></i> profile</a></li>
              </ul>
              <li class="nav-item">
                <a class="nav-link text-dark fw-bold" href="#"></a>              
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark fw-bold" aria-current="page" href="#"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark fw-bold" aria-current="page" href="#"></a>
              </li>
              </ul>
          
        </div>
      </div>
    </nav>
    {% block content %} 

    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

customer/templates/customer/my cart.html
{% extends "customer/master.html" %}
{% load static %}
{% block content %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">sno</th>
          <th scope="col">customer name</th>
          <th scope="col">product name</th>
          <th scope="col">product img</th>
          <th scope="col">product price</th>
          <th scope="col">product quantity</th>
          <th scope="col">total price</th>

        </tr>
      </thead>
      <tbody>
        {% for item in cart %}
        <tr>
          <th scope="row">1</th>
          <td>{{ item.customer.first_name }} {{ item.customer.second_name }}</td>
          <td>{{ item.Product.product_name }}</td>
          <td><img src="{{ item.Product.image.url }}" class="card-img-top" alt="..." style="height: 100px; width: 100px;"></td>
          <td>{{ item.Product.price }}</td>
          <td><input type="number" min="1" value="1" max="{{ item.Product.stock }}" id="qty{{ forloop.counter }}" data-item="{{ item.Product.id }}" ></td>
          <td><input type="text" readonly id="amt{{ item.Product.id }}" value="{{ item.Product.price }}" class="total"></td>
          <td><button class="btn btn-success">buy now</button></td>
          <td><a class="text-decoration-none text-danger" href="{% url 'customer:remove_cart_item' item.id %}"> remove</a></td>
        </tr>
        {% endfor %}
        
        
      </tbody>
    </table>
    
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <script>
   

   $(document).ready(function(){
    display_amount()
    $.ajaxSetup({
            headers: {
              "X-CSRFToken": '{{ csrf_token }}'
            }
        })
        $("input").change(function(){
          let qty =$(this).val()
          let pid =$(this).attr('data-item')
          
          $.ajax({
            url:"{% url 'customer:get_total' %}",
            data:{
              'qty': qty,
              'pid': pid,

            },
            method : 'POST',
            success: function(response){
              $('#amt'+pid).val(response.amount)
              display_amount()
              console.log(response.amount)
            }
          })
        })

   
   })
function display_amount(){
  let  limit =document.querySelectorAll('.total')
    let total =0
    for (let i = 0; i <limit.length; i++) {
       total = total+parseInt(limit[i].value)
      
    }
    console.log(total)
}
    </script>
  {% endblock %}

customer/templates/customer/product details.html
{% extends "customer/master.html" %}
{% load static %}
{% block content %}

    <div class="container mt-4">
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-4">
            <form method="POST">
          {% csrf_token %}
            <img src="{{ details.image.url }}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title fs-4 fw-bold text-warning text-uppercase">{{ details.product_name }}</h5>
              <p class="card-text">{{ details.product_discription }}</p>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
              <span class="text-dark fs-5"><i class="fa-solid fa-indian-rupee-sign"></i>{{ details.price }}</span> <br>
              <div class="card-footer">
              <button class="btn btn-outline-danger" type="submit">add to cart</button>
              <button class="btn btn-outline-primary" type="submit">Buy now</button> <br>{{ message }}
            </div>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endblock %}

customer/templates/customer/profile.html
{% extends "customer/master.html" %}
{% load static %}
{% block content %}
  <div class="container">
    <div class="row mt-4">
      <div class="col-sm-12 mt-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-center">My profile</h5>
            <div class="text-center mt-4">
              <img src="{% static 'images/flutter-course-training-calicut-kerala.png' %}" alt=""
                style="width: 100px;height: 100px;" class="border border-dark">
            </div>
            <div class="text-end">
            <button  class="btn btn-link updatebutton" data-bs-toggle="modal" href="#exampleModalToggle" role="button" type="button" id="updatebutton" data-item="{{ profile.id }}"><i class="fa-solid fa-pen-to-square fs-2 text-dark me-3"></i></button>
            </div>
            <div class="alert  alert-danger alert-dismissible fade show" role="alert" id="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            <div class="container mt-4">
              <div class="row">
                <div class="col-sm-12">
                  <div class="card">
                    <div class="card-body">
                      <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">First Name:</th>
                            <td>{{ profile.first_name }}</td>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <th scope="col">Second Name:</th>
                            <td>{{ profile.second_name }}</td>

                          </tr>
                          <tr>
                            <th scope="col">Email:</th>
                            <td>{{ profile.email }}</td>

                          </tr>
                          <tr>
                            <th scope="col">Phone Number:</th>
                            <td>{{ profile.phone }}</td>

                          </tr>
                          <tr>
                            <th scope="col">Address:</th>
                            <td>{{ profile.address }}</td>

                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>

              </div>
            </div>
            

          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalToggleLabel">Modal 1</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
              <div class="col mb-2">
                <input type="text" class="form-control form-control-sm" placeholder="First name"  style="width: 60%;" id="fname" name="First_name">
              </div>
              <div class="col mb-2">
                <input type="text" class="form-control form-control-sm" placeholder="Last name"  style="width: 60%;" id="sname" name="Last_name">
              </div>
            
            <div class="col mb-2">
              <textarea class="form-control address"  rows="3" placeholder="Address" style="width: 60%;"  name="address"></textarea>
              </div>
            <div class="col mb-2">
              <input type="tel" class="form-control form-control-sm"  value="{{ profile.phone }}" style="width: 60%;" disabled>
            </div>
            <div class="col mb-2">
              <input type="email" class="form-control form-control-sm" value="{{ profile.email }}"  style="width: 60%;" disabled>
            </div>
            <div class="col mb-2">
              <input type="file" class="form-control form-control-sm"   style="width: 60%;">
            </div>
            
            <div class="col mb-2">
              <button type="submit" class="btn btn-outline-success updatebutton" style="width: 25%;" id="liveToastBtn"><i class="fa-solid fa-pen-to-square"></i> update</button>
            </div>
          </form>
        </div>
        <div class="modal-footer">
         
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>

  <script>
    $(document).ready(function(){
      
      str = $('div.alert').text();
   if($.trim(str) === "") {
     $('div.alert').hide();
   }
    $.ajaxSetup({
            headers: {
              "X-CSRFToken": '{{ csrf_token }}'
            }
        })
        $("#updatebutton").click(function(){
          let proid = $(this).attr('data-item')
          
          $.ajax({
            url:"{% url 'customer:profile_ajax' %}",
            data:{
              'proid': proid,

            },
            method : 'POST',
            success: function(response){
              $('#fname').val(response.f_name)
              $('#sname').val(response.s_name)
              $('.address').val(response.c_add)
              
            }
          })
        })
        
        
      })
  </script>
{% endblock %}