common/urls.py
from django.urls import path
from.import views
app_name='common'

urlpatterns=[
  path('master',views.home,name='cmaster'),
  path('home',views.customer_login,name='chome'),
  path('customersignup',views.customer_signup,name='customer_signup'),
  path('projecthome',views.project_home,name='home'),
  path('sellerlogin',views.seller_login,name='seller_login'),
  path('sellersignup',views.seller_signup,name='seller_signup'),
  path('customer_login',views.customer_login,name='customer_login'),
  path('index',views.index,name='index'),
  path('float',views.float,name='float'),
]

ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('customer.urls')),
    path('ecom_admin/',include('ecom_admin.urls')),
    path('seller/',include('seller.urls')),
    path('',include('common.urls')),
    path('lightapi/',include('lightapi.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from.import views 
app_name='seller'

urlpatterns=[
  path('home',views.home,name='home'),
  path('addproduct',views.add_product),
  path('changepassword',views.change_password),
  path('productcatalog',views.product_catalog),
  path('profile',views.profile),
  path('updatestock',views.update_stock,name='updatestock'),
  path('stock_number',views.stock_number,name='stock_number'),
  path('profile_ajax',views.profile_ajax,name='profile_ajax'),
]

seller/models.py
from django.db import models
from common.models import seller

# Create your models here.


class Product(models.Model):
   seller = models.ForeignKey(seller,on_delete=models.CASCADE)
   product_name = models.CharField(max_length=20)
   category_name = models.CharField(max_length=20)
   product_number = models.BigIntegerField()
   product_discription =models.CharField(max_length=60)
   price = models.IntegerField()
   stock = models.IntegerField()
   image = models.ImageField(upload_to='product/')
   
   class Meta:
      db_table = 'product_tb'

seller/views.py
from django.shortcuts import render
from .models import Product
from common.models import seller
from django.http import JsonResponse

# Create your views here.
def home(request):
    seller_details = seller.objects.get(id=request.session['seller'])
    product = Product.objects.filter(seller_id =request.session['seller'])
    sname = seller_details.first_name+' '+seller_details.second_name
    context ={
       'name':sname,
       'products':product,
    }
    return render(request,'seller/home.html',context)
      

def add_product(request):
    if request.method == 'POST':
      p_name =request.POST['product_name']
      p_category = request.POST['product_category']
      p_number =request.POST['product_number']
      p_disc =request.POST['product_dis']
      p_quantity =request.POST['product_quantity']
      
      p_price =request.POST['product_price']
    
      p_img = request.FILES['product_img'] 
      seller = request.session['seller']
      new_product = Product(product_name =p_name,category_name =p_category,product_number =p_number,
      product_discription=p_disc,price =p_price,stock=p_quantity,image =p_img,seller_id = seller)
    
      
      new_product.save()

    return render(request,'seller/add product.html')

def change_password(request):
    error_msg = ''
    success_msg = ''
    if request.method == 'POST':
      old_password = request.POST['old_password']
      new_password = request.POST['new_password']
      conform_password = request.POST['conform_password']
      if new_password == conform_password:
        if len(new_password) > 8:
            Seller = seller.objects.get(id =request.session['seller'])
            if old_password == Seller.password:
                Seller.password = new_password
                Seller.save()
                success_msg = 'successfully created new password'
            else:
                error_msg ='invalid password'
        else:
            error_msg = 'password should be minimum 8 characters'
      else:
        error_msg ='password does\'t match'
    return render(request,'seller/change password.html',{'error':error_msg,'success':success_msg})
  
def product_catalog(request):
    return render(request,'seller/product catalog.html')

def profile(request):
    seller_details = seller.objects.get(id=request.session['seller'])
    return render(request,'seller/profile.html',{'profile':seller_details})

def update_stock(request):
    product = Product.objects.filter(seller_id =request.session['seller'])
    if request.method == 'POST':
        
        prodid =request.POST['pid']
        print(prodid)
        
        new_stock =request.POST['new_stock']
        product1 =Product.objects.get(id=prodid)
        product1.stock += int(new_stock)
        
        product1.save()
    return render(request,'seller/update stock.html',{'products':product})

def stock_number(request):
    qty = request.POST['qty']
    product = Product.objects.filter(id=qty).values('product_name','stock')
    p_name = product[0]['product_name']
    p_stock = product[0]['stock']
    return JsonResponse({'pname':p_name,'pstock': p_stock})

def profile_ajax(request):
    proid =request.POST['proid']
    profile = seller.objects.filter(id=proid).values('first_name','second_name','address')
    f_name =profile[0]['first_name'] 
    l_name =profile[0]['second_name']
    s_address =profile[0]['address']
    
    return JsonResponse({'fname':f_name,'l_name':l_name,'s_address':s_address})


    

seller/templates/seller/add product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'style/sellerhome.css' %}">
    <link rel="stylesheet" href="{% static 'style/main.css' %}">
</head>
<body>
  <div class="mt-5 ms-5">
    <form  method="Post" enctype="multipart/form-data">
  {% csrf_token %}
    <div class="mb-2">
      <label for="exampleInputproductname" class="form-label">Product name</label>
      <input type="text" class="form-control form-control-sm" id="exampleInputproductname" aria-describedby="emailHelp" style="width: 70%;" name="product_name">
      
    </div>
    <div class="mb-2">
      <label for="exampleInputproductname" class="form-label">Product number</label>
      <input type="text" class="form-control form-control-sm" id="exampleInputproductname" aria-describedby="emailHelp" style="width: 70%;" name="product_number">
      
    </div>
    <div class="mb-2">
    <label for="exampleInputselect" class="form-label">category name</label>
    <select class="form-select form-select-sm" aria-label=".form-select-sm example" style="width: 70%;" name="product_category">
      <option selected>select product</option>
      <option value="1">wall light</option>
      <option value="2">kitchen light</option>
      <option value="3">bathroom light</option>
    </select>
  </div>
    <div class="mb-2">
      <label for="exampleFormControlTextarea1" class="form-label">product discription</label>
      <textarea class="form-control form-control-sm" id="exampleFormControlTextarea1" rows="3" style="width: 70%;" name="product_dis"></textarea>
    </div>
    <div class="mb-2">
      <label for="exampleInputquantity" class="form-label">quantity</label>
      <input type="number" class="form-control form-control-sm" id="exampleInputquantity" style="width: 25%;" name="product_quantity">
    </div>
    <div class="mb-2">
      <label for="exampleInputprice" class="form-label">price</label>
      <input type="tel" class="form-control form-control-sm" id="exampleInputprice" style="width: 25%;" name="product_price">
    </div>
    
    <div class="mb-2">
      <label for="exampleInputimg" class="form-label">Choose a image</label>
      <input type="file" class="form-control form-control-sm" id="exampleInputimg" style="width: 25%;" name="product_img">
    </div>
    <div class="mb-2 form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
  </form>



 
</div>

</body>
</html>

seller/templates/seller/change password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style/style.css' %}">
  

</head>
<body>
  <div class="container">
    
      <div class="row g-0">
        
        <div class="col-md-4  mt-5 pt-5 rounded-3">
          <img src="{% static 'images/lohin-img.jpg' %}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body color mt-5 pt-5 rounded-3">
            <h5 class="card-title ms-5">Seller login</h5>
            <div class="mt-4 ms-4">
              <form method="post">
              {% csrf_token %}
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label">old password</label>
                  <input type="password" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" style="width: 50%;" name="old_password">
                  
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">new Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" style="width: 50%;" name="new_password">
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">conform Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" style="width: 50%;" name="conform_password">
                </div>
                <div class="mb-3 form-check">
                  <input type="checkbox" class="form-check-input" id="exampleCheck1">
                  <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-outline-danger mb-3" style="width: 25%;">change</button>
                {{ error }} {{ success }}
              </form>
            </div>
            <!-- <div class="modal-footer justify-content-center">
              <div class="mb-3">
             <span>create a new account?</span><a class="text-decoration-none text-danger" href="{% url 'common:seller_signup' %}" >sign up</a>
            </div>
            </div> -->
          </div>
        </div>
      </div>
    
  </div>
  
</body>
</html>

seller/templates/seller/home.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'style/sellerhome.css' %}">
    <link rel="stylesheet" href="{% static 'style/main.css' %}">
    <link rel="stylesheet" href="{% static 'style/grid.css' %}">
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-transparent">
      <div class="container-fluid">
        <a class="navbar-brand text-dark fw-bold" href="#"><span class="text-danger">L!ght</span>-k@rt</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <form class="d-flex" role="search">
            <input class="form-control me-2 rounded-pill" type="search" placeholder="Search" aria-label="Search" style="width:400px;">
            <button class="btn btn-outline-dark rounded-circle" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
          </form>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link text-dark fw-bold" href="#"><i class="fa-brands fa-dropbox fs-5 text-primary"></i> product</a>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-link fs-6 text-dark text-decoration-none fw-bold" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="fa-solid fa-cart-plus fs-5 text-info"></i> Add product</button> 
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark fw-bold" href="#"></a>            
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-plus fs-5 text-danger"></i>
              </a>
              <ul class="dropdown-menu dropdown-menu-end">
                <li><a class="dropdown-item" href="#"><i class="fa-solid fa-truck fs-5 text-danger"></i>  order history</a></li>
                <li><a class="dropdown-item" href="#"><i class="fa-solid fa-truck-fast fs-5"></i>  Recent order</a></li>
                <li><a class="dropdown-item" href="#"><i class="fa-solid fa-calendar-plus fs-5"></i>   updatestock</a></li>
                <li><a class="dropdown-item" href="#"><i class="fa-solid fa-key fs-5 text-warning"></i>  change password</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#"><i class="fa-solid fa-lock fs-5 text-success"></i>  logout</a></li>
                <li><a class="dropdown-item" href="#"><i class="fa-solid fa-user fs-5 text-secondary"></i> profile</a></li>
              </ul>
              <li class="nav-item">
                <a class="nav-link text-dark fw-bold" href="#"></a>              
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark fw-bold" aria-current="page" href="#"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark fw-bold" aria-current="page" href="#"></a>
              </li>
              </ul>
          
        </div>
      </div>
    </nav> 
    <div class="row">
      <div class="col">
        <!-- <img src="{% static 'images/graph (1).png' %}" class="img-fluid" alt=""> -->
        <div class="mt-5 pt-5 ps-4">
          <h1 class="fw-bold text-color">Welcome {{ name }} to the world of light</h1>
          <h1 class="fw-bold text-color">be part of us and grow with us!!!!</h1>
        </div>
      

      </div>
      <div class="col">
        <img src="{% static 'images/main-removebg-preview.png' %}" class="img-fluid main-img" alt="">
      </div>
    </div>
    <div class="row">
      {% for product in products  %}
      <div class="col-sm-2">
        
        <div class="card border border-0">
          <img src="{{ product.image.url }}" class="card-img-top" alt="...">
          <div class="card-body border border-0">
            <h5 class="card-title">{{ product.product_name}}</h5>
            <p class="card-text">{{ product.product_discription }}
            </p>
            <span class="text-muted fs-4"><s> <span class="text-dark">&#8377;</span> 1000 </s><span
                class="text-danger">350 OFF</span> </span>
  
            <div>
              <span class="text-danger fs-4"><span class="text-dark text-end">&#8377;</span>{{ product.price }}</span>
  
            </div>
          </div>
        </div>
      </div>
      {% endfor %}

    </div>

    <!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header bg-danger">
        <h1 class="modal-title fs-5 text-light" id="exampleModalLabel">Add Product</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-2">
            <label for="exampleInputproductname" class="form-label">Product name</label>
            <input type="text" class="form-control form-control-sm" id="exampleInputproductname" aria-describedby="emailHelp" style="width: 70%;">
            
          </div>
          <div class="mb-2">
          <label for="exampleInputselect" class="form-label">product category</label>
          <select class="form-select form-select-sm" aria-label=".form-select-sm example" style="width: 70%;">
            <option selected>select product</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
          </select>
        </div>
          <div class="mb-2">
            <label for="exampleFormControlTextarea1" class="form-label">product discription</label>
            <textarea class="form-control form-control-sm" id="exampleFormControlTextarea1" rows="3" style="width: 70%;"></textarea>
          </div>
          <div class="mb-2">
            <label for="exampleInputquantity" class="form-label">quantity</label>
            <input type="number" class="form-control form-control-sm" id="exampleInputquantity" style="width: 25%;">
          </div>
          <div class="mb-2">
            <label for="exampleInputprice" class="form-label">price</label>
            <input type="tel" class="form-control form-control-sm" id="exampleInputprice" style="width: 25%;">
          </div>
          
          <div class="mb-2">
            <label for="exampleInputimg" class="form-label">Choose a image</label>
            <input type="file" class="form-control form-control-sm" id="exampleInputimg" style="width: 25%;">
          </div>
          <div class="mb-2 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
          </div>
          
        </form>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Add</button>
      </div>
    </div>
  </div>
</div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

seller/templates/seller/product catalog.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <div class="container mt-4">
      <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{% static 'images/lightone.jpg' %}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

seller/templates/seller/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
</head>
<body>
  <div class="container">
    <div class="row mt-4">
      <div class="col-sm-12 mt-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-center">My profile</h5>
            <div class="text-center mt-4">
              <img src="{{ profile.seller_pic.url }}" alt=""
                style="width: 100px;height: 100px;" class="border border-dark">
            </div>
            <div class="text-end">
              <button  class="btn btn-link updatebutton" data-bs-toggle="modal" href="#exampleModalToggle" role="button" type="button" id="updatebutton" data-item="{{ profile.id }}"><i class="fa-solid fa-pen-to-square fs-2 text-dark me-3"></i></button>
              </div>
              <div class="alert  alert-danger alert-dismissible fade show" role="alert" id="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            <div class="container mt-4">
              <div class="row">
                <div class="col-sm-12">
                  <div class="card">
                    <div class="card-body">
                      <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">First Name:</th>
                            <td>{{ profile.first_name }}</td>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <th scope="col">Second Name:</th>
                            <td>{{ profile.second_name }}</td>

                          </tr>
                          <tr>
                            <th scope="col">Email:</th>
                            <td>{{ profile.email }}</td>

                          </tr>
                          <tr>
                            <th scope="col">Phone Number:</th>
                            <td>{{ profile.phone }}</td>

                          </tr>
                          <tr>
                            <th scope="col">Address:</th>
                            <td>{{ profile.address }}</td>

                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>

              </div>
            </div>
            <div class="text-end mt-4">
              <button class="btn btn-outline-primary">update profile</button>
            </div>

          </div>
        </div>

      </div>
    </div>

    <div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalToggleLabel">Modal 1</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
                <div class="col mb-2">
                  <input type="text" class="form-control form-control-sm" value="{{ profile.first_name }}"  style="width: 60%;"  name="First_name">
                </div>
                <div class="col mb-2">
                  <input type="text" class="form-control form-control-sm" value="{{ profile.second_name }}"  style="width: 60%;"  name="Last_name">
                </div>
              
              <div class="col mb-2">
                <textarea class="form-control"  rows="3"  style="width: 60%;"  name="address"></textarea>
                </div>
              <div class="col mb-2">
                <input type="tel" class="form-control form-control-sm"  value="{{ profile.phone }}" style="width: 60%;" disabled>
              </div>
              <div class="col mb-2">
                <input type="email" class="form-control form-control-sm" value="{{ profile.email }}"  style="width: 60%;" disabled>
              </div>
              <div class="col mb-2">
                <input type="file" class="form-control form-control-sm"   style="width: 60%;">
              </div>
              
              <div class="col mb-2">
                <button type="submit" class="btn btn-outline-success updatebutton" style="width: 25%;" id="liveToastBtn"><i class="fa-solid fa-pen-to-square"></i> update</button>
              </div>
            </form>
          </div>
          <div class="modal-footer">
           
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function(){
        
        str = $('div.alert').text();
     if($.trim(str) === "") {
       $('div.alert').hide();
     }
      $.ajaxSetup({
              headers: {
                "X-CSRFToken": '{{ csrf_token }}'
              }
          })
          // $("#updatebutton").click(function(){
            // let proid = $(this).attr('data-item')
            // alert('hai')
            proid =$("#fname").attr('data-item')
            
            $.ajax({
              url:"{% url 'seller:profile_ajax' %}",
              data:{
                'proid': proid,
  
              },
              method : 'POST',
              success: function(response){
                $('#fname').val(response.fname)
                $('#sname').val(response.l_name)
                $('#address').val(response.s_address)
                
                
              }
            })
          // })
          
          
        })
    </script>
</body>

</html>

seller/templates/seller/update stock.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

</head>
<body>
  <div class="container">
  <div class="row">
    <div class="col-sm-12 mt-5">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">update stock here!</h5>
          <form  method="POST" enctype="multipart/form-data">
            {% csrf_token %}
          <select class="form-select form-select-sm" aria-label=".form-select-sm example" name="pid" id="cid">
            <!-- <option selected>select product number</option> -->
            {% for product in products  %}
            <option value="{{ product.id }}" >{{ product.product_number }}</option>

            
            
            {% endfor %}
           
          </select>  <br>
          <label for="">product name:</label> 
          <input type="text" id="product_number"> <br> <br>
          <label for="">current stock:</label> 
          <input type="text" id="current_stock"> <br> <br>
          
          <label for="">new stock:</label> 
          <input type="number" name="new_stock" min="1"> <br> <br>
          
          <button class="btn btn-primary" type="submit">update stock</button>
          
        </form>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
<script>
  $(document).ready(function(){
    $.ajaxSetup({
            headers: {
              "X-CSRFToken": '{{ csrf_token }}'
            }
        })
    $("select").change(function(){
          let qty =$(this).val()
          
          $.ajax({
            url:"{% url 'seller:stock_number' %}",
            data:{
              'qty': qty,
               

            },
            method : 'POST',
            success: function(response){
              $('#product_number').val(response.pname)
              $('#current_stock').val(response.pstock)
            
              
            }
            
            
          })
        })
        
  })
</script>
</html>