common/urls.py
from django.urls import path
from.import views
app_name='common'

urlpatterns=[
  path('master',views.home,name='cmaster'),
  path('home',views.customer_login,name='chome'),
  path('customersignup',views.customer_signup,name='customer_signup'),
  path('projecthome',views.project_home,name='home'),
  path('sellerlogin',views.seller_login,name='seller_login'),
  path('sellersignup',views.seller_signup,name='seller_signup'),
  path('customer_login',views.customer_login,name='customer_login'),
  path('index',views.index,name='index'),
  path('float',views.float,name='float'),
]

customer/urls.py
from django.urls import path
from. import views 
app_name='customer'

urlpatterns=[
 path('home',views.home,name='home'),
 path('changepassword',views.change_password,name='changepassword'),
 path('checkout',views.checkout),
 path('mycart',views.my_cart,name='cart1'),
 path('myorder',views.my_order),
 path('productdetails/<int:pid>',views.product_details,name="productdetails1"),
 path('profile',views.profile,name='profile'),
 path('master',views.master),
 path('get_total',views.get_total,name='get_total'),
 path('remove_cart/<int:cid>',views.remove_cart_item,name='remove_cart_item'),
 path('logout',views.log_out,name='logout'),
 path('profile_ajax',views.profile_ajax,name='profile_ajax'),
]

ecom_admin/urls.py
from django.urls import path
from . import views 
app_name='ecom_admin'

urlpatterns=[
  path('home',views.home),
  path('approveseller',views.approveseller,name='approveseller'),
  path('viewseller',views.viewseller),
  path('viewcustomer',views.viewcustomer),
  path('viewproduct',views.view_product,name='view_product'),
  
]

ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('customer.urls')),
    path('ecom_admin/',include('ecom_admin.urls')),
    path('seller/',include('seller.urls')),
    path('',include('common.urls')),
    path('lightapi/',include('lightapi.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecom_admin/models.py
from django.db import models

# Create your models here.

ecom_admin/views.py
from django.shortcuts import render ,redirect
from common.models import seller
from seller.models import Product

# Create your views here.

def home(request):
    return render(request,'ecom_admin/home.html')

def approveseller(request):
    
    if request.method == 'POST':
        pid =request.POST['sid']
        if 'btn_approve' in request.POST:
            seller.objects.filter(id=pid).update(action='Approved')

        if 'btn_reject' in request.POST:
            seller.objects.filter(id=pid).update(action='Reject')
         
    seller_details =seller.objects.filter(action='Pending')
    return render(request,'ecom_admin/approve seller.html',{'seller_details': seller_details})
   
def viewcustomer(request):
    return render(request,'ecom_admin/view customer.html')  

def viewseller(request):
    return render(request,'ecom_admin/view seller.html')  

def view_product(request):
    all_product =Product.objects.all()

    return render(request,'ecom_admin/view_product.html',{'all_product':all_product})   

# def rejectseller(request,sid):
#     seller_details =seller.objects.all()
#     print(sid)
    
#     return render(request,'ecom_admin/approve seller.html')

ecom_admin/templates/ecom_admin/approve seller.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="row mt-5">
        <div class="col-sm-12">
          <div class="card">
            <div class="card-header">Seller details</div>
            <div class="card-body">
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">S No</th>
                    <th scope="col">Name</th>
                    <th scope="col">E mail</th>
                    <th scope="col">phone</th>
                    <th scope="col">profile pic</th>
                    
                    <th scope="col">action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for seller in seller_details %}
                  <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ seller.first_name }} {{ seller.second_name }} </td>
                    <td>{{ seller.email }}</td>
                    <td>{{ seller.phone }}</td>
                    <td> <img src="{{ seller.seller_pic.url }}" alt="" style="width: 60px; height: 60px; border-radius: 60px;"></td>
                    
                    <td>
                    <button type="submit" class="btn btn-primary" name="btn_approve" >approve</button>
                     <button type="submit" class="btn btn-danger" name="btn_reject" >Reject</button>
                      
                    </td>
                    <td><input type="hidden" name="sid" value="{{ seller.id }}"></td>
                  </tr>
                </form>
                 {% endfor %}
                  
                </tbody>
              </table>
            </div>
          </div>
        </div>
        
      </div>
    </div>
    
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

ecom_admin/templates/ecom_admin/home.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-transparent">
      <div class="container-fluid">
        <a class="navbar-brand text-dark fw-bold" href="#"><span class="text-danger">L!ght</span>-k@rt</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <form class="d-flex" role="search">
            <input class="form-control me-2 rounded-pill" type="search" placeholder="Search" aria-label="Search" style="width:400px;">
            <button class="btn btn-outline-dark rounded-circle" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
          </form>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
           
            <li class="nav-item mt-2 me-2">
              <a class="text-decoration-none text-dark fs-6 fw-bold" href="{% url 'customer:cart1' %}"><i class="fa-solid fa-truck fs-5 text-danger"></i> my cart</a></li>
            </li>
           
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-plus fs-5 text-danger"></i>
              </a>
              <ul class="dropdown-menu dropdown-menu-end">
                
                <li><a class="dropdown-item" href="#"><i class="fa-solid fa-truck-fast fs-5"></i>  Recent order</a></li>
                <li><a class="dropdown-item" href="#"><i class="fa-solid fa-calendar-plus fs-5"></i>   updatestock</a></li>
                <li><a class="dropdown-item" href="{% url 'customer:changepassword' %}"><i class="fa-solid fa-key fs-5 text-warning"></i>  change password</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'customer:logout' %}"><i class="fa-solid fa-lock fs-5 text-success"></i>  logout</a></li>
                <li><a class="dropdown-item" href="{% url 'customer:profile' %}"><i class="fa-solid fa-user fs-5 text-secondary"></i> profile</a></li>
              </ul>
              <li class="nav-item">
                <a class="nav-link text-dark fw-bold" href="#"></a>              
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark fw-bold" aria-current="page" href="#"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark fw-bold" aria-current="page" href="#"></a>
              </li>
              </ul>
          
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body text-center">
             <a href="{% url 'ecom_admin:approveseller' %}" class="text-decoration-none"><i class="fa-solid fa-user-check fs-1"></i><h1 class="fs-5 ">Approve seller</h1></a>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body text-center">
              <a href="" class="text-decoration-none"><i class="fa-solid fa-eye fs-1"></i><h1 class="fs-5 ">View customer</h1></a>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body text-center">
              <a href="" class="text-decoration-none"><i class="fa-solid fa-users-viewfinder fs-1"></i><h1 class="fs-5 ">View seller</h1></a>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body text-center">
              <a href="" class="text-decoration-none"><i class="fa-solid fa-user-minus fs-1"></i><h1 class="fs-5 ">Remove seller</h1></a>

              
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body text-center">
              <a href="" class="text-decoration-none"><i class="fa-solid fa-user-minus fs-1"></i><h1 class="fs-5 ">Remove customer</h1></a>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body text-center">
              <a href="" class="text-decoration-none"><i class="fa-solid fa-cart-shopping fs-1"></i><h1 class="fs-5 ">View product</h1></a>
            </div>
          </div>
        </div>
      </div>
    </div>

   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

ecom_admin/templates/ecom_admin/view customer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h2>view customer</h2>
</body>
</html>

ecom_admin/templates/ecom_admin/view seller.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>view seller</h1>
</body>
</html>

ecom_admin/templates/ecom_admin/view_product.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <div class="row g-2">
        {% for product in all_product %}
      <div class="col-sm-3">
      <div class="card border-success">
        <img src="{{ product.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title text-primary">{{ product.product_name }}</h5>
          <p class="card-text">added by : {{ product.seller.first_name |upper }} {{ product.seller.second_name | upper }}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">product price : {{ product.price }}</li>
          <li class="list-group-item">product quantity : {{ product.stock }}</li>
          <li class="list-group-item">product number : {{ product.product_number }}</li>
        </ul>
        
      </div>
    </div>
    {% endfor %}
    </div>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>