common/urls.py
from django.urls import path
from.import views
app_name='common'

urlpatterns=[
  path('master',views.home,name='cmaster'),
  path('home',views.customer_login,name='chome'),
  path('customersignup',views.customer_signup,name='customer_signup'),
  path('projecthome',views.project_home,name='home'),
  path('sellerlogin',views.seller_login,name='seller_login'),
  path('sellersignup',views.seller_signup,name='seller_signup'),
  path('customer_login',views.customer_login,name='customer_login'),
  path('index',views.index,name='index'),
  path('float',views.float,name='float'),
]

ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('customer.urls')),
    path('ecom_admin/',include('ecom_admin.urls')),
    path('seller/',include('seller.urls')),
    path('',include('common.urls')),
    path('lightapi/',include('lightapi.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
   first_name = models.CharField(max_length=20)
   second_name = models.CharField(max_length=20)
   email = models.CharField(max_length=50)
   password =models.CharField(max_length=20)
   phone = models.BigIntegerField()
   address = models.TextField()
   
   class Meta:
      db_table = 'customer_tb'

class seller(models.Model):
   first_name = models.CharField(max_length=50)
   second_name = models.CharField(max_length=50)
   email = models.CharField(max_length=30)
   password = models.CharField(max_length=20)
   user_name = models.IntegerField(default=0)
   phone = models.BigIntegerField()
   address = models.TextField()
   bank_name = models.CharField(max_length=20)
   account_number = models.BigIntegerField()
   ifsc = models.CharField(max_length=10)
   seller_pic = models.ImageField(upload_to='seller/')
   action =models.CharField(max_length=20,default='Pending')

   class Meta:
      db_table = 'seller_tb'

common/views.py
from django.shortcuts import render ,redirect
from .models import Customer
from .models import seller
from random import randint
from django.conf import settings
from django.core.mail import send_mail
from rest_framework.response import Response
from rest_framework.decorators import api_view
import logging

logger =logging.getLogger('django')
# Create your views here.
def home(request):
    logger.info('this is info message')
    return render(request,'common/master.html')

def customer_login(request):
    return render(request,'common/home.html')

def customer_signup(request):
    if request.method == 'POST':
        f_name =request.POST['customerfirstname']
        l_name = request.POST['customerlastname']
        c_address =request.POST['customeraddress']
        c_phone =request.POST['customerphone']
        c_email =request.POST['customeremail']
        c_password =request.POST['customerpassword']
        new_customer = Customer(first_name=f_name,second_name=l_name,email=c_email,password=c_password,phone=c_phone,address=c_address)
        new_customer.save()

    return render(request,'common/customer signup.html')

def project_home(request):
    return render(request,'common/project home.html')

def seller_login(request):
    
    msg = ''
    if request.method  == "POST":
        email = request.POST['email']
        password = request.POST['password']
        try: 
            Seller = seller.objects.get(user_name = email, password = password)   #model_name= post_name
            if Seller.action =="Approved":
                request.session['seller'] = Seller.id
                return redirect('seller:home') #redirect(app_name:url_name)
            else:
                msg ='Admin Rejected you'    
        except Exception as e:
            print (e)   #to check error
            msg = 'Invalid credentials'

    


    return render(request,'common/seller login.html',{'message':msg})

def seller_signup(request):
    if request.method == 'POST':
      f_name =request.POST['sellerfirstname']
      l_name = request.POST['sellerlastname']
      s_address =request.POST['selleraddress']
      s_phone =request.POST['sellerphone']
      s_email =request.POST['selleremail']
      
      s_bankname =request.POST['sellerbankname']
      user_name1 = randint(1111,9999)
      s_password = 'sell-'+str(user_name1)+'-'+s_phone[6:10]
      s_accountnum =request.POST['selleraccountnumber']
      s_ifsc =request.POST['sellerifsc'] 
      s_img = request.FILES['sellerimg'] 
      new_seller = seller(first_name=f_name,second_name=l_name,email=s_email,password=s_password,phone=s_phone,address=s_address,
      bank_name =s_bankname,account_number=s_accountnum,ifsc=s_ifsc,seller_pic=s_img,user_name=user_name1)
      email_subject = 'Account username and password'
      email_content = 'hai your username will be:  '+ str(user_name1)+' and password will be: '+s_password
      send_mail(
        email_subject,
        email_content,
        settings.EMAIL_HOST_USER,
        [s_email,],
        fail_silently = False
      )
      new_seller.save()
      
 
    return render(request,'common/seller signup.html')

def customer_login(request):
    msg = ''
    if request.method  == "POST":
        email = request.POST['email']
        password = request.POST['password']
        try: 
            customer = Customer.objects.get(email = email, password = password)   #model_name= post_name
            request.session['customer'] = customer.id
            return redirect('customer:home') #redirect(app_name:url_name)
        except Exception as e:
            print (e)   #to check error
            msg = 'Invalid credentials'

    return render(request,'common/customer_login.html',{'message':msg})
    # return render(request,'common/customer_login.html')
@api_view(['GET'])
def index(request):
    return Response('congratulation, you have created an api')

@api_view(['GET'])
def float(request):
    return Response(4.5)

common/templates/common/customer signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'style/style.css' %}">
  <link rel="icon" href="{% static 'favicon/revu.ico' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style/mystyle.css' %}">

</head>
<body>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-8">
          <div class="mt-5 ms-4">
            <h1 class="mb-3 fs-3">Customer signup</h1>
          <form  method="Post">
            {% csrf_token %}
            <div class="col mb-2">
              <input type="text" class="form-control form-control-sm" placeholder="First name" aria-label="First name" style="width: 80%;" name="customerfirstname">
            </div>
            <div class="col mb-2">
              <input type="text" class="form-control form-control-sm" placeholder="Last name" aria-label="Last name" style="width: 80%;" name="customerlastname">
            </div>
          
          <div class="col mb-2">
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Address" style="width: 80%;" name="customeraddress"></textarea>
            </div>
          <div class="col mb-2">
            <input type="tel" class="form-control form-control-sm" placeholder="Phonenumber" aria-label="First name" style="width: 80%;" name="customerphone">
          </div>
          <div class="col mb-2">
            <input type="email" class="form-control form-control-sm" placeholder="Email" aria-label="email" style="width: 80%;" name="customeremail">
          </div>
          <div class="col mb-2">
            <input type="password" class="form-control form-control-sm" placeholder="Password" aria-label="password" style="width: 80%;" name="customerpassword">
          </div>
          <div class="col mb-2">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
          </div>
          <div class="col mb-2">
            <button type="submit" class="btn btn-outline-success" style="width: 25%;">Sign up</button>
          </div>
        </form>
      </div>
        </div>
        <div class="col-sm-4">
        <img src="{% static 'images/lamp1.png' %}" alt="" style="height: 400px; width: 400px;">
        </div>
      </div>
    </div>
    
  </body>
</html>

common/templates/common/customer_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

</head>
<body>
  <div class="container">
    <div class="row g-0">
      <div class="col-md-4 mt-5">
        <img src="{% static 'images/login.jpg' %}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8 mt-5 border-start border-danger border-4 ">
        <div class="card-body">
          <h5 class="card-title ms-5">Customer login</h5>
          <div class="mt-4 ms-5">
            <form method="post">
            {% csrf_token %}
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" style="width: 50%;"  name="email">
                
              </div>
              <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" style="width: 50%;" name="password">
              </div>
              <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
              </div>
              <button type="submit" class="btn btn-outline-danger" style="width: 25%;">Login</button>
              {{ message }}
            </form>
          </div>
          <div class="modal-footer justify-content-center">
           <span>create a new account?</span><a class="text-decoration-none text-danger"  href="{% url 'common:customer_signup' %}">sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  
</body>
</html>

common/templates/common/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'style/mystyle.css' %}">
  <link rel="stylesheet" href="{% static 'style/grid.css' %}">
  <link rel="icon" href="{% static 'favicon/favicon.ico' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">

</head>
<body>
  <nav class="navbar navbar-expand-lg bg-transparent">
    <div class="container-fluid">
      <a class="navbar-brand text-dark fw-bold" href="#"><span class="text-danger">L!ght</span>-k@rt</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="d-flex" role="search">
          <input class="form-control me-2 rounded-pill" type="search" placeholder="Search" aria-label="Search" style="width:400px;">
          <button class="btn btn-outline-dark rounded-circle" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          
          <!-- <li class="nav-item">
            <a class="nav-link text-dark fw-bold" href="#"> <i class="fa-solid fa-cart-plus fs-5"></i> Cart</a>
          </li> -->
          <li class="nav-item me-2">
            <a class="text-decoration-none text-dark fw-bold" href="{% url 'common:customer_login' %}"><i class="fa-solid fa-user fs-5"></i></a>
          </li>
          <!-- #exampleModalToggle -->
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-user"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><a class="dropdown-item" href="#">Login</a></li>
              <li><a class="dropdown-item" href="#"></a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul> -->
            <li class="nav-item">
              <a class="text-decoration-none text-dark fw-bold"  href="{% url 'common:seller_login' %}">seller</a>
            </li>
            
            </ul>
        
      </div>
    </div>
  </nav>


  <div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
    <div class="modal-dialog  modal-lg">
      <div class="modal-content modal-bg-color">
        <div class="modal-header">
          <h1 class="modal-title fs-4" id="exampleModalToggleLabel">Login</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form>
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" style="width: 50%;" placeholder="We'll never share your email with anyone else.">
              
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" style="width: 50%;">
            </div>
            <div class="mb-3 form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-outline-success" style="width: 25%;">Login</button>
          </form>
        </div>
        <div class="modal-footer justify-content-center">
         <span>create a new account?</span><button class="btn btn-link text-success" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal">sign up</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
    <div class="modal-dialog modal-lg">
      <div class="modal-content modal-bg-color">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalToggleLabel2">Sign up</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form  method="post">
            {% csrf_token %}
            <div class="col mb-2">
              <input type="text" class="form-control form-control-sm" placeholder="First name" aria-label="First name" style="width: 60%;" name="customerfirstname">
            </div>
            <div class="col mb-2">
              <input type="text" class="form-control form-control-sm" placeholder="Last name" aria-label="Last name" style="width: 60%;" name="customerlastname">
            </div>
          
          <div class="col mb-2">
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Address" style="width: 60%;" name="customeraddress"></textarea>
            </div>
          <div class="col mb-2">
            <input type="tel" class="form-control form-control-sm" placeholder="Phonenumber" aria-label="First name" style="width: 60%;" name="customerphone">
          </div>
          <div class="col mb-2">
            <input type="email" class="form-control form-control-sm" placeholder="Email" aria-label="email" style="width: 60%;" name="customeremail">
          </div>
          <div class="col mb-2">
            <input type="password" class="form-control form-control-sm" placeholder="Password" aria-label="password" style="width: 60%;" name="customerpassword">
          </div>
          <div class="col mb-2">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
          </div>
          <div class="col mb-2">
            <button type="submit" class="btn btn-outline-success" style="width: 25%;">Sign up</button>
          </div>
        </form>
        </div>
        <!-- <div class="mb- form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-outline-success" style="width: 25%;">Login</button> -->
        <div class="modal-footer justify-content-center">
          
          <span>Already have an account?</span><button class="btn btn-link text-success" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Login Here</button>
        </div>
      </div>
    </div>
  </div>
  

  <!-- -----------------------------seller modal---------------------------------------- -->

  <div class="modal fade" id="exampleModalseller" aria-hidden="true" aria-labelledby="exampleModalseller" tabindex="-1">
    <div class="modal-dialog  modal-lg">
      <div class="modal-content modal-bg-color2">
        <div class="modal-header">
          <h1 class="modal-title fs-4" id="exampleModalseller"> seller Login</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="post">
            <div class="mb-3">
              <label for="exampleInputtext1" class="form-label">Username</label>
              <input type="text" class="form-control" id="exampleInputtext1" aria-describedby="emailHelp" style="width: 50%;">
              
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword2" class="form-label">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword2" style="width: 50%;">
            </div>
            <div class="mb-3 form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-outline-success" style="width: 25%;">Login</button>
          </form>
        </div>
        <div class="modal-footer justify-content-center">
         <span>create a new account?</span><button class="btn btn-link text-success" data-bs-target="#exampleModalseller2" data-bs-toggle="modal">sign up</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="exampleModalseller2" aria-hidden="true" aria-labelledby="exampleModalseller" tabindex="-1">
    <div class="modal-dialog modal-lg">
      <div class="modal-content modal-bg-color2">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalseller">seller Sign up</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="post">
          {% csrf_token %}
            <div class="col mb-2">
              <input type="text" class="form-control form-control-sm" placeholder="First name" aria-label="First name" style="width: 60%;">
            </div>
            <div class="col mb-2">
              <input type="text" class="form-control form-control-sm" placeholder="Last name" aria-label="Last name" style="width: 60%;">
            </div>
          
          <div class="col mb-2">
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Address" style="width: 60%;"></textarea>
            </div>
          <div class="col mb-2">
            <input type="tel" class="form-control form-control-sm" placeholder="Phonenumber" aria-label="First name" style="width: 60%;">
          </div>
          <div class="col mb-2">
            <input type="email" class="form-control form-control-sm" placeholder="Email" aria-label="First name" style="width: 60%;">
          </div>
          <div class="col mb-2">
            <input type="password" class="form-control form-control-sm" placeholder="Password" aria-label="First name" style="width: 60%;">
          </div>
          <div class="col mb-2">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
          </div>
          <div class="col mb-2">
            <button type="submit" class="btn btn-outline-success" style="width: 25%;">Sign up</button>
          </div>
        </form>
        </div>
        <!-- <div class="mb- form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-outline-success" style="width: 25%;">Login</button> -->
        <div class="modal-footer justify-content-center">
          
          <span>Already have an account?</span><button class="btn btn-link text-success" data-bs-target="#exampleModalToggle" data-bs-toggle="modal">Login Here</button>
        </div>
      </div>
    </div>
  </div>

{% block content %}

{% endblock %}


<div class="container-fluid">
  <footer class="py-3 my-4 " style="background-color: #3B2C28;">
    <ul class="nav justify-content-center border-bottom pb-1 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-light">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-light">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-light">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-light">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-light">About</a></li>
    </ul>
    <p class="text-center text-light">© 2022 Company, Inc</p>
  </footer>
</div>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>

 

</html>

common/templates/common/project home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Vishnuchengot</title>
  <link rel="stylesheet" href="{% static 'style/mystyle.css' %}">
  <link rel="icon" href="{% static 'favicon/favicon.ico' %}">
  <link href="https://fonts.googleapis.com/css2?family=Merienda+One&family=Roboto&display=swap" rel="stylesheet">
  
  
</head>
<body>
  <div class="top-container">
    <div class="navbar">
      <img class="github-img" src="{% static 'images/github.png' %}" alt=""> <a class="github-link" href="">GIT HUB</a>
     <img class="call" src="{% static 'images/call.png' %}" alt=""> <h2 class="number">+91 9072879546</h2>
    </div>
    <img class="bulb"  src="{% static 'images/lightbulb.png' %}" alt=" circuit image">
    <img class="pcb-board"  src="{% static 'images/electrical-circuit.png' %}" alt=" circuit image">
    <h1 class="main-name">Vishnu_chengot</h1>
    <h3 class="main-discription"> a web developer</h3>
  <img class="circuit"  src="{% static 'images/bio-sensor.png' %}" alt=" circuit image">
  </div>
  <div class="middle-background">
   <div class="middle-container">
    <img class="my-profile" src="{% static 'images/myimage.jpg' %}" alt="">
    <h2 class="heading">Hello..</h2>
    <p>A Web Developer who creates Responsive Websites and Web applications.I <span>&#10084;</span> biryani.</p>
    
  </div>
     <br><hr>
    <div class="skill-row">
    <h2 class="heading">MY SKILLS</h2> <BR></BR>
    <span class="sub-heading">DESIGN AND DEVELOPMENT</span>
    <img class="web-development-img" src="{% static 'images/web-development.png' %}" alt="">
    <p> I Started learning to code recently becacuse of my long term interest.Overtime I have gained some experience
    in designing and developing web sites and web applications.
    </p>
    </div>
    <div class="skill-row">
    <img class="bio-sensor-img" src="{% static 'images/bio-sensor.png' %}" alt="">
    <span class="sub-heading">ELECTRONICS HOBBYIST</span>
    <p> Some Good Sound in development of Electronic hobby circuits.Building hobby circuit is more fun to learn the technology. </p>
    
  </div>
  <hr>
  </div>
</body>
</html>

common/templates/common/seller login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style/style.css' %}">
  

</head>
<body>
  <div class="container">
    
      <div class="row g-0">
        
        <div class="col-md-4  mt-5 pt-5 rounded-3">
          <img src="{% static 'images/lohin-img.jpg' %}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body color mt-5 pt-5 rounded-3">
            <h5 class="card-title ms-5">Seller login</h5>
            <div class="mt-4 ms-4">
              <form method="post">
              {% csrf_token %}
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label">User name</label>
                  <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" style="width: 50%;" name="email">
                  
                </div>
                <div class="mb-3">
                  <label for="exampleInputPassword1" class="form-label">Password</label>
                  <input type="password" class="form-control" id="exampleInputPassword1" style="width: 50%;" name="password">
                </div>
                <div class="mb-3 form-check">
                  <input type="checkbox" class="form-check-input" id="exampleCheck1">
                  <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-outline-danger" style="width: 25%;">Login</button>
                {{ message }}
              </form>
            </div>
            <div class="modal-footer justify-content-center">
              <div class="mb-3">
             <span>create a new account?</span><a class="text-decoration-none text-danger" href="{% url 'common:seller_signup' %}" >sign up</a>
            </div>
            </div>
          </div>
        </div>
      </div>
    
  </div>
  
</body>
</html>